# Generated by Django 5.1 on 2024-09-14 16:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cast_member_app', '0001_initial'),
        ('category_app', '0001_initial'),
        ('genre_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVideoMediaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('raw_location', models.CharField(max_length=255)),
                ('encoded_location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('PROCESSING', 'processing'), ('COMPLETED', 'completed'), ('ERROR', 'error')], default='pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMediaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('raw_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('launch_year', models.IntegerField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opened', models.BooleanField()),
                ('published', models.BooleanField()),
                ('rating', models.CharField(choices=[('ER', 'ER'), ('L', 'L'), ('AGE_10', 'age_10'), ('AGE_12', 'age_12'), ('AGE_14', 'age_14'), ('AGE_16', 'age_16'), ('AGE_18', 'age_18')], max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('banner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_app.imagemediamodel')),
                ('cast_members', models.ManyToManyField(related_name='videos', to='cast_member_app.castmembermodel')),
                ('categories', models.ManyToManyField(related_name='videos', to='category_app.categorymodel')),
                ('genres', models.ManyToManyField(related_name='videos', to='genre_app.genremodel')),
                ('thumbnail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail', to='video_app.imagemediamodel')),
                ('thumbnail_half', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail_half', to='video_app.imagemediamodel')),
                ('trailer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_trailer', to='video_app.audiovideomediamodel')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_media', to='video_app.audiovideomediamodel')),
            ],
            options={
                'db_table': 'video',
                'ordering': ['-created_at'],
            },
        ),
    ]
